// Mocks generated by Mockito 5.4.6 from annotations
// in movies/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:movies/core/api/remote/api_response.dart' as _i10;
import 'package:movies/features/home/data/datasources/api/movie_service.dart'
    as _i12;
import 'package:movies/features/home/data/datasources/movie_data_source.dart'
    as _i9;
import 'package:movies/features/home/data/models/movie_detail_model.dart'
    as _i5;
import 'package:movies/features/home/data/models/movie_response_model.dart'
    as _i4;
import 'package:movies/features/home/domain/entities/movie.dart' as _i8;
import 'package:movies/features/home/domain/entities/movie_detail.dart' as _i3;
import 'package:movies/features/home/domain/entities/page_result.dart' as _i2;
import 'package:movies/features/home/domain/repositories/movie_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePageResult_0<T> extends _i1.SmartFake implements _i2.PageResult<T> {
  _FakePageResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetail_1 extends _i1.SmartFake implements _i3.MovieDetail {
  _FakeMovieDetail_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieResponseModel_2 extends _i1.SmartFake
    implements _i4.MovieResponseModel {
  _FakeMovieResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailModel_3 extends _i1.SmartFake
    implements _i5.MovieDetailModel {
  _FakeMovieDetailModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i6.MovieRepository {
  @override
  _i7.Future<_i2.PageResult<_i8.Movie>> getPopular({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getPopular, [], {#page: page}),
            returnValue: _i7.Future<_i2.PageResult<_i8.Movie>>.value(
              _FakePageResult_0<_i8.Movie>(
                this,
                Invocation.method(#getPopular, [], {#page: page}),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.PageResult<_i8.Movie>>.value(
                  _FakePageResult_0<_i8.Movie>(
                    this,
                    Invocation.method(#getPopular, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i2.PageResult<_i8.Movie>>);

  @override
  _i7.Future<_i2.PageResult<_i8.Movie>> getTopRated({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getTopRated, [], {#page: page}),
            returnValue: _i7.Future<_i2.PageResult<_i8.Movie>>.value(
              _FakePageResult_0<_i8.Movie>(
                this,
                Invocation.method(#getTopRated, [], {#page: page}),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.PageResult<_i8.Movie>>.value(
                  _FakePageResult_0<_i8.Movie>(
                    this,
                    Invocation.method(#getTopRated, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i2.PageResult<_i8.Movie>>);

  @override
  _i7.Future<_i3.MovieDetail> getDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDetail, [id]),
            returnValue: _i7.Future<_i3.MovieDetail>.value(
              _FakeMovieDetail_1(this, Invocation.method(#getDetail, [id])),
            ),
            returnValueForMissingStub: _i7.Future<_i3.MovieDetail>.value(
              _FakeMovieDetail_1(this, Invocation.method(#getDetail, [id])),
            ),
          )
          as _i7.Future<_i3.MovieDetail>);

  @override
  _i7.Future<_i2.PageResult<_i8.Movie>> search(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query], {#page: page}),
            returnValue: _i7.Future<_i2.PageResult<_i8.Movie>>.value(
              _FakePageResult_0<_i8.Movie>(
                this,
                Invocation.method(#search, [query], {#page: page}),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i2.PageResult<_i8.Movie>>.value(
                  _FakePageResult_0<_i8.Movie>(
                    this,
                    Invocation.method(#search, [query], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i2.PageResult<_i8.Movie>>);
}

/// A class which mocks [MovieDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDataSource extends _i1.Mock implements _i9.MovieDataSource {
  @override
  _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>> getPopular({
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPopular, [], {#page: page}),
            returnValue:
                _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>>.value(
                  _i11.dummyValue<_i10.ApiResponse<_i4.MovieResponseModel>>(
                    this,
                    Invocation.method(#getPopular, [], {#page: page}),
                  ),
                ),
            returnValueForMissingStub:
                _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>>.value(
                  _i11.dummyValue<_i10.ApiResponse<_i4.MovieResponseModel>>(
                    this,
                    Invocation.method(#getPopular, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>>);

  @override
  _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>> getTopRated({
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTopRated, [], {#page: page}),
            returnValue:
                _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>>.value(
                  _i11.dummyValue<_i10.ApiResponse<_i4.MovieResponseModel>>(
                    this,
                    Invocation.method(#getTopRated, [], {#page: page}),
                  ),
                ),
            returnValueForMissingStub:
                _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>>.value(
                  _i11.dummyValue<_i10.ApiResponse<_i4.MovieResponseModel>>(
                    this,
                    Invocation.method(#getTopRated, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>>);

  @override
  _i7.Future<_i10.ApiResponse<_i5.MovieDetailModel>> getDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDetail, [id]),
            returnValue:
                _i7.Future<_i10.ApiResponse<_i5.MovieDetailModel>>.value(
                  _i11.dummyValue<_i10.ApiResponse<_i5.MovieDetailModel>>(
                    this,
                    Invocation.method(#getDetail, [id]),
                  ),
                ),
            returnValueForMissingStub:
                _i7.Future<_i10.ApiResponse<_i5.MovieDetailModel>>.value(
                  _i11.dummyValue<_i10.ApiResponse<_i5.MovieDetailModel>>(
                    this,
                    Invocation.method(#getDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i10.ApiResponse<_i5.MovieDetailModel>>);

  @override
  _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>> search(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query], {#page: page}),
            returnValue:
                _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>>.value(
                  _i11.dummyValue<_i10.ApiResponse<_i4.MovieResponseModel>>(
                    this,
                    Invocation.method(#search, [query], {#page: page}),
                  ),
                ),
            returnValueForMissingStub:
                _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>>.value(
                  _i11.dummyValue<_i10.ApiResponse<_i4.MovieResponseModel>>(
                    this,
                    Invocation.method(#search, [query], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i10.ApiResponse<_i4.MovieResponseModel>>);
}

/// A class which mocks [MovieService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieService extends _i1.Mock implements _i12.MovieService {
  @override
  _i7.Future<_i4.MovieResponseModel> getPopularMovies({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, [], {#page: page}),
            returnValue: _i7.Future<_i4.MovieResponseModel>.value(
              _FakeMovieResponseModel_2(
                this,
                Invocation.method(#getPopularMovies, [], {#page: page}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.MovieResponseModel>.value(
              _FakeMovieResponseModel_2(
                this,
                Invocation.method(#getPopularMovies, [], {#page: page}),
              ),
            ),
          )
          as _i7.Future<_i4.MovieResponseModel>);

  @override
  _i7.Future<_i4.MovieResponseModel> getTopRatedMovies({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, [], {#page: page}),
            returnValue: _i7.Future<_i4.MovieResponseModel>.value(
              _FakeMovieResponseModel_2(
                this,
                Invocation.method(#getTopRatedMovies, [], {#page: page}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.MovieResponseModel>.value(
              _FakeMovieResponseModel_2(
                this,
                Invocation.method(#getTopRatedMovies, [], {#page: page}),
              ),
            ),
          )
          as _i7.Future<_i4.MovieResponseModel>);

  @override
  _i7.Future<_i5.MovieDetailModel> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i7.Future<_i5.MovieDetailModel>.value(
              _FakeMovieDetailModel_3(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.MovieDetailModel>.value(
              _FakeMovieDetailModel_3(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i5.MovieDetailModel>);

  @override
  _i7.Future<_i4.MovieResponseModel> searchMovies({
    required String? query,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [], {#query: query, #page: page}),
            returnValue: _i7.Future<_i4.MovieResponseModel>.value(
              _FakeMovieResponseModel_2(
                this,
                Invocation.method(#searchMovies, [], {
                  #query: query,
                  #page: page,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.MovieResponseModel>.value(
              _FakeMovieResponseModel_2(
                this,
                Invocation.method(#searchMovies, [], {
                  #query: query,
                  #page: page,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.MovieResponseModel>);
}
